### ISSUE TITLE
require_once missing, and paths not working.

### ISSUE THREAD

**Issue by mnott** [vaakash/git-it-write#14]
Hi there,

you've an awesome plugin there. I blogged about it here: [http://www.mnott.de/obsidian-for-wordpress/](http://www.mnott.de/obsidian-for-wordpress/). I had to do some modifications, as I wrote on that blog - I had to require_once media.php, file.php and image.php, and also I had to do some changes in parsedown.php so that I could make the image paths work.

Also, updating a post sometimes seems not to happen at all - I don't know how long to wait for it to actually appear on the page. I think it will do it eventually, but sometimes it is instantaneous, sometimes not really. Look at the Caveats at the bottom of the page.

But regardless; I use it together with [Obsidian](https://obsidian.md), which has a huge community. I think your plugin is really great. Thanks!

**Comment by vaakash** [comment]
Hi @mnott,

Thanks for using Git it write.
Sorry for the late reply.

I'll go over the issues you've reported and address them in the next version.

Thanks,
Aakash
