### ISSUE TITLE
How to copy directly .md file data

### ISSUE THREAD

**Issue by contactosama** [vaakash/git-it-write#19]
ie. I wanted to copy content of this link: https://github.com/abbodi1406/C2R-R2V-AIO/blob/master/README.md

**Comment by vaakash** [comment]
Hi @contactosama,

As of now the plugin will pull all files ending with `.md`.
In you case it seem there is only one `.md` file in the repository.
You can add this repo in the plugin settings and pull the changes. It will pick only the readme.md file.

If you want to skip certain files, then please add `skip_file: yes` in the YAML header.

Thanks,
Aakash

**Comment by lukaszpiotrluczak** [comment]
@contactosama I am not sure if I understand correctly. 

Do you want to include contents of some other file in your post/page md?
