### ISSUE TITLE
All posts duplicate

### ISSUE THREAD

**Issue by drbeco** [vaakash/git-it-write#2]
Every time I write a new post, and commit/push, all the old posts are duplicated.

* Using webhook
* There should be a configuration to allow only new posts to be published

Thanks

**Comment by wvpv** [comment]
I'm having the same issue when posting to pages.  I'm publishing from the root of the repository with the "Pages (Hierarchical, Public)" option selected.  Every time I push an update to Github it adds another page instead of updating the one with the matching slug.
