### ISSUE TITLE
Images not uploaded with private Github repo

### ISSUE THREAD

**Issue by myannou** [vaakash/git-it-write#20]
Hello,
I configured the plugin (Git-it-write 1.6) to use a private Github repo. 
So I configured the Github username + Access token
but the images (located in the _images directory) are not uploaded
And I get the following error: " Image upload failed for some reason"

```
11/27/2022 08:28 - Starting image chain
11/27/2022 08:28 - Uploading image chain
11/27/2022 08:28 - {"type":"file","raw_url":"https:\/\/raw.githubusercontent.com\/sokube\/blogs-private\/main\/_images\/chain.png","github_url":"https:\/\/github.com\/sokube\/blogs-private\/blob\/main\/_images\/chain.png","sha":"3793f048d95239d3ddadc9d1f48ca3727e417f65","file_type":"png"}
11/27/2022 08:28 - Image upload failed for some reason
```

I noticed that the access token is not appended to the query (https://raw.githubusercontent.com/....?token=XXX)

Switching to a public repo make it works...

**Comment by lukaszpiotrluczak** [comment]
Hi :) 
I have just encourted the same issue, investigated and patched. But now it is 1 am and I feel too sleepy to check it and push merge request. 
I will do it tomorrow and hopefully it will be quickly merged.

**Comment by myannou** [comment]
Thank you for the fix
When do you plan to publish a new version of Git-it-write with this fix ?

**Comment by myannou** [comment]
I confirm this work correctly with private repo
Thanks
