### ISSUE TITLE
Plugin cannot be activated due to missing files (composer instructions in README missing)

### ISSUE THREAD

**Issue by DoItWithASmile** [vaakash/git-it-write#22]
The 'vendor' directory is included in git ignore, which makes sense.

Checked v1.5 and v1.6. The released ZIPs do not include the generated composer files.
Option A: include vendor directory in released packages

In addition, the README does not mention to run composer after unpacking the files and before activating the plugin in WordPress.
Option B: amend installation section in README

**Comment by vaakash** [comment]
Hi @DoItWithASmile, Yes I just noticed it. The v1.6 release zip file does not contain the "vendor" directory. 

The zip file is now correct in the latest release v1.7.
