### ISSUE TITLE
RWD images 

### ISSUE THREAD

**Issue by TWME-TW** [vaakash/git-it-write#25]
The pictures in the article do not support automatic scaling, the following is the result of my attempt to use the original editor and git-it-write:

original editor page https://architectmc.com/start/

git-it-write page  https://architectmc.com/getting-started/ (password `test`)
( GitHub https://github.com/mc-builderintw-net/ArchitectMC/blob/main/getting-started.md )
![Screenshot_20230104_184103_Chrome](https://user-images.githubusercontent.com/65117253/210537779-9a5864f3-9a58-4a3f-a310-3158fe521f49.jpg)
![Screenshot_20230104_184112_Chrome](https://user-images.githubusercontent.com/65117253/210537786-a197b63c-2eda-4f10-ac1f-16a6570154f9.jpg)

**Comment by vaakash** [comment]
This is addressed in v1.7. Marking this as closed.
