### ISSUE TITLE
Can future consider supporting formats,like: [[wikilink]] ![[wikilink]]

### ISSUE THREAD

**Issue by jarlin8** [vaakash/git-it-write#26]
Can future consider supporting formats 👍 [[wikilink]] ![[wikilink]]  writen .md files by obsidian.

**Comment by vaakash** [comment]
Hi @jarlin8, Git it write supports relative and absolute links. I would suggest to use them to link to internal files. https://www.aakashweb.com/docs/git-it-write/writing-posts/#using-links
