### ISSUE TITLE
special characters not supported in post properties

### ISSUE THREAD

**Issue by myannou** [vaakash/git-it-write#30]
special characters like single quote (') or colon (:) in post properties (Title, post_excerpt, ...)
Generate error when synchronizing articles:

`Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 6 (near "Il s'intègre particulièrement..."`

**Comment by vaakash** [comment]
Hi @myannou, the error looks like YAML formatting error. The plugin does support UTF characters set as post title, description. Please refer below document for YAML syntax - https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
