### ISSUE TITLE
ability to configure the slug through post properties

### ISSUE THREAD

**Issue by myannou** [vaakash/git-it-write#31]
As mentionned in the doc:

`Git it write considers the file name as the post slug i.e if the name of the file is getting-started.md then the post slug is getting-started.`

Would it be possible to configure the slug through post properties
So that it is explicit and make it possible to have 2 files in the same dir with the same slug
usecase with multi-lang where the slang is the same and the lang is in the url of the link:
* my-domain.com/en/blog/my-blog-post
* my-domain.com/fr/blog/my-blog-post

**Comment by vaakash** [comment]
Hi @myannou, Unfortunately, this would not be possible. The filename decides the post slug. The plugin is designed in such a way that the filename is a key part. The filename acts as an anchor and it cannot be changed based on the contents. In your case, you can create two folders with `en` and `fr` and hav `.md` files as per that language.
