### ISSUE TITLE
How to use a code highlight plugin with code-it-write

### ISSUE THREAD

**Issue by myannou** [vaakash/git-it-write#32]
I would like to use a code highlight plugin like https://wordpress.org/plugins/code-block-pro/
But I don't know how to make it write with code-it-write ?

**Comment by vaakash** [comment]
Hi @myanno, When you add a code block in markdown - https://www.markdownguide.org/basic-syntax/#code, then the code is wrapped with `<pre>` tag. This is the standard behavior. It would be better if code block pro plugin can recognize such `<pre>` tags and activate the syntax highlighting on that.
