### ISSUE TITLE
Use of .html files, without conversion

### ISSUE THREAD

**Issue by RedstoneFuture** [vaakash/git-it-write#35]
Hi. What do you think about the possibility to upload also ".html" files where there is no Markdown->HTML conversion.

I have post content with more than just Markdown text, as it contains more complex HTML/WordPress content, such as:

```
[sc name="shorturl"][/sc]

<p class="article_description">[icon name="chevron-right" prefix="fas"] Demo text 1234.<p>

<img class="article-image" src="/media/demo/picture1.gif" alt="" />

<h2>Characteristics</h2>
```

EDIT: I just see in the [FAQ](https://www.aakashweb.com/docs/git-it-write/faq/#what-all-files-in-the-repository-will-be-published) that it is already being planned. I would be very happy if the feature was developed in the future. Actually, everything necessary has already been programmed. I need it for a complex multilingual documentation setup.

**Comment by vaakash** [comment]
Hi @RedstoneFuture,

Thanks for the suggestion. I did think about including raw html files but didn't implement it since there were no requests. I have added this to my todo list. I'll implement this ASAP in the upcoming versions of the plugin.

**Comment by RedstoneFuture** [comment]
> Hi @RedstoneFuture,
> 
> Thanks for the suggestion. I did think about including raw html files but didn't implement it since there were no requests. I have added this to my todo list. I'll implement this ASAP in the upcoming versions of the plugin.

I'm glad to hear that. Thank you very much! :)

**Comment by RedstoneFuture** [comment]
I would be very happy if this is still possible this year. I want to start a bigger documentation project next year and for that the workflow has to be ready. If that is possible. :)

**Comment by vaakash** [comment]
Hi @RedstoneFuture,

Sure, I would be happy to add that feature. I'll be releasing a version to target WordPress 6.4. I'll include the change to pull HTML files in that before Nov mid/end in that release.

Thanks,
Aakash

**Comment by vaakash** [comment]
Hi @RedstoneFuture,

I just forgot that we can always use HTML inside in markdown files. You can use HTML with all tags and attributes. Note that the file extension must remain `.md` and the file must still have the YAML header for the post metadata. I have updated the docs with this information. Please try and update the same.
