### ISSUE TITLE
Export wordpress posts to markdown

### ISSUE THREAD

**Issue by tblobaum** [vaakash/git-it-write#38]
This might be a bit much to ask for, as this plugin already does a lot. However, I think this plugin could be a lot more popular if there is an ability to export existing wordpress posts into the markdown format used by the plugin. What do you think?

**Comment by vaakash** [comment]
Hi @tblobaum,

I guess this is beyond the plugin's scope and idea. To export wordpress posts to markdown I believe we should make use of other plugins. 

PS: GIW works in the one way i.e markdown files are published to WordPress and not vice versa. So any change made in a post will not be pushed back to the markdown file.

**Comment by tblobaum** [comment]
I totally understand. Do you see how the plugin could become much more popular if this is added, though? Then people could migrate existing blogs to GIW. On Nov 12, 2023, at 5:33 AM, Aakash Chakravarthy ***@***.***> wrote:﻿
Hi @tblobaum,
I guess this is beyond the plugin's scope and idea. To export wordpress posts to markdown I believe we should make use of other plugins.
PS: GIW works in the one way i.e markdown files are published to WordPress and not vice versa. So any change made in a post will not be pushed back to the markdown file.

**Comment by vaakash** [comment]
Hi @tblobaum,
I understand, this plugin was actually created for my personal website where I want to write posts in markdown format and version control in Github. I later decided to make it open and available for all.

Anything beyond this would not personally help me or my website. With your requirement, I don't see it helping me considering the efforts and research needed to be put for the nieche audience this plugin serves.
