### ISSUE TITLE
Every time a new post is created, multiple articles are generated simultaneously. After deletion, they are generated again. However, there is no problem when updating existing data.

### ISSUE THREAD

**Issue by jarlin8** [vaakash/git-it-write#39]
Every time a new post is created, multiple articles are generated simultaneously. After deletion, they are generated again. However, there is no problem when updating existing data.
- wordpress 6.4.1
- git-it-write 1.8
<img width="128" alt="1703864827921" src="https://github.com/vaakash/git-it-write/assets/81870669/cf3fc8dc-10d4-4c40-b37a-2eecbc2c41b8">
<img width="322" alt="1703864803964" src="https://github.com/vaakash/git-it-write/assets/81870669/3420dfb3-65cc-47b3-8e4d-520dcf024065">

**Comment by vaakash** [comment]
Hi, 

Could you please share the repository URL and a screenshot of the repo settings in GIW plugin?

I'll try to reproduce the issue.

Regarding posts getting generated on delete, that is expected. Unless .md files are deleted in the repo, post will be created.

**Comment by jarlin8** [comment]
yes, thank you!
- https://github.com/jarlin8/fendou.la/
<img width="571" alt="1703897117816" src="https://github.com/vaakash/git-it-write/assets/81870669/786a404f-aae3-49af-8d1f-deee13877d6d">

**Comment by jarlin8** [comment]
When I try to update using the button `pull only changes` in the WordPress plugin backend, it works fine, but when pushing a new file to the GitHub repository, it creates a lot of duplicate posts.
![image](https://github.com/vaakash/git-it-write/assets/81870669/bfe0ed15-8152-428a-b946-8825a920b67a)

**Comment by jarlin8** [comment]
add: i'm using the githubToken push to the GitHub repository.
maybe this is the reason, have test that when using the githubToken push to the GitHub repository, creates duplicate posts.
when push by git or Github Desktop,work fine.

**Comment by vaakash** [comment]
Hi @jarlin8,

I tried your repository and I'm not able to reproduce the issue.

Everytime I do "push from changes", I can see that the posts are not duplicated.
They are published only once.

![image](https://github.com/vaakash/git-it-write/assets/299561/ae7595af-dc5a-4cd2-a88f-07aba9c59304)

Note:
The filename is the ID for the post (i.e post-slug). if that post slug/filename is not present then new post will be created.

I would suggest testing on a folder with less files to identify the issue.

The type of publish "github push or desktop" does not matter. The plugin uses same logic to publish posts.

Thanks,
Aakash

**Comment by jarlin8** [comment]
Thank you for your hard work in testing and responding. The situation you tested indeed has no issues. However, there are problems with using the githubToken push to the GitHub repository, creates duplicate posts.  I tested another file called 'testid' and still created two articles.,Here is my log. Thanks!
https://raw.githubusercontent.com/jarlin8/fendou.la/main/fendou-posts/log.txt

**Comment by vaakash** [comment]
Hi @jarlin8,

It seems the Github push event is sent multiple times.

Can you please go to Repository -> Settings -> WebHook -> Edit the webhook.

Under settings tab, please ensure "just the push event" is selected.

Under "recent deliveries" tab, ensure only one event is pushed by Github whenver you make a commit.

Thanks,
Aakash

**Comment by jarlin8** [comment]
![image](https://github.com/vaakash/git-it-write/assets/81870669/b95a45f6-1215-4495-a9f0-4238c370698f)
![image](https://github.com/vaakash/git-it-write/assets/81870669/817df1a6-06fb-454e-b27c-baec1dd3f683)
"recent deliveries" tab,have so many event?

**Comment by vaakash** [comment]
Hi @jarlin8,
We can see more than one push events in Github for the same commit.
Can you please review how you are making these commits? Please check online too to avoid this issue.

We should see only one push event for one commit.

![image](https://github.com/vaakash/git-it-write/assets/299561/045c6556-f6b9-42b8-9056-06268741a0dd)

**Comment by jarlin8** [comment]
thank you @vaakash  i will check my program

**Comment by tblobaum** [comment]
@vaakash deserves a coffee for this one
