### ISSUE TITLE
Unable to pull files that have multiple "." in the filename

### ISSUE THREAD

**Issue by pacepace** [vaakash/git-it-write#41]
I have a bunch of release notes that have filenames in the format of "Server-12.3.0.md" where the version in the file name uses "." as the separator between the major, minor and patch numbers.  These files are not imported by git-it-write.  If I change the filename to use "_" as the separator then the file imports.

**Comment by vaakash** [comment]
Hi @pacepace, I'll check and get back to you on this.

**Comment by pacepace** [comment]
Fixed in most recent version.
