### ISSUE TITLE
Updating images

### ISSUE THREAD

**Issue by Seshpenguin** [vaakash/git-it-write#52]
If an commit updates an image on the repo, the plugin does not update the image (unless it is deleted from Wordpress first).

**Comment by vaakash** [comment]
Hi @Seshpenguin,

Thanks for using GIW. Yes that is expected. The plugin does not recognize image changes. Deleting an existing image should be done manually as it might be linked to multiple other posts. I would suggest the method you have described manually.

Thanks,
Aakash
