### ISSUE TITLE
Private Github repos not working ?

### ISSUE THREAD

**Issue by neps-in** [vaakash/git-it-write#7]
Hey Akash,

Private repos are not working , hence made them public, or how to use private repos to work with webhooks

**Comment by neps-in** [comment]
looks like its not supported any plans in near future.

**Comment by eamodio** [comment]
@vaakash Are there any plans to support private repositories? Is it a big/involved task?

**Comment by vaakash** [comment]
Hi @eamodio Earlier, the plugin was accessing the GitHub repo details using the free public API. Recently I added authentication to Github using an access token. I didn't check if that would work for private repositories. I'll check that out and let you know in a couple of days.

**Comment by lukaszpiotrluczak** [comment]
Now this mainly works. The only issue was with image in private repo. I have provided PR with fix for it.
