### ISSUE TITLE
Error when pushing md file with image

### ISSUE THREAD

**Issue by FedericaLionetto** [vaakash/git-it-write#9]
Hi,

I am trying to push to Wordpress a md file that contains text and one image but I get the error reported in the log below. 
Both the md file and the image are located on the main branch, the md file in a folder called "post/en/travels/" and the image in a folder called "_images/".
Wordpress is configured to pull from the folder "post" only and to publish according to the format "post".
In the md file, I tried to reference the image by using the relative path or the absolute path, but none of the two worked.

Any hints what could be the reason and how to fix it?

Thank you very much for your help.

[log.txt](https://github.com/vaakash/git-it-write/files/8643240/log.txt)

**Comment by guillermomf2001** [comment]
Try to move the `_images` folder to the root folder of your repository and then link them using the path `/_images/image.jpg`

**Comment by mnott** [comment]
As I found out and described [here](http://www.mnott.de/obsidian-for-wordpress/), I had to require_once media.php, file.php and image.php, to publisher.php.
